# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

# Copy csproj first for layer caching
COPY *.csproj ./

RUN dotnet restore

# Copy remaining files
COPY . ./

RUN dotnet publish -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/runtime:10.0

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "TelemetryRabbitClient.dll"]

# docker build -t telemetry-client . 
# docker run -it --rm telemetry-client